### PR TITLE
Little Re-design of website

### PR DESCRIPTION
**Pull request by krmnn**
This is a litte redesign of our website:
- only one shade of blue
- no more blocksatz/justify text
- fixed broken html in joblist
- menu with visual distinct submenu
- company logo only on landing page 

screenshot 2019-02-02 at 10 06 27
screenshot 2019-02-02 at 10 06 38

### CODE REVIEW

**Comment by hellerve** [comment]
Thanks! This looks pretty good to me. @hugurp could you maybe review this?

**Comment by jonbecker** [comment]
i like it as well!! I really don't see any need to have the GDPR sub-menu permanently displayed, but if it has to be, this is a much better solution than the current design.

**Comment by krmnn** [comment]
lists

**Comment by hugurp** [comment]
lgtm

**Pull request merged**
